import com.sample.Message;
 
rule "Filter"
	when
		m : Message(Message.getMessage == "Message to filter");
	then
		m.setMessage( "Filtered message" );
		System.out.println(m.getMessage());
end

rule "Time"
	when
		m : Message(Message.getTimeStamp != null);
	then
		System.out.println("Message sent at: " + m.getTimeStamp());
		System.out.println("Latency: " + (m.getTimeNow() - m.getTimeStamp()));
end