import it.cnr.isti.labse.cmb.event.SimpleEvent;
import it.cnr.isti.labse.cmb.settings.DebugMessages;

declare SimpleEvent
	@role( event )
	@timestamp( timestamp )
end

/*rule "Filter"
no-loop
	when
		$objA : SimpleEvent();
		$objB : SimpleEvent(this.data == $objA.data, this.timestamp != $objA.timestamp);
	then
		System.out.println("------------------------------------MATCHING-OCCURS-----------------------------------");

		System.out.println($objA.getID() + " " +
		$objA.getData() + " con timestamp: " + $objA.getTimestamp()
		+ " E' UGUALE A " +
		$objB.getData() + " con timestamp: " + $objB.getTimestamp());
		DebugMessages.line();
end*/

rule "Time"
	no-loop
	when
		$aEvent : SimpleEvent();
		$bEvent : SimpleEvent( this before[ 20s, 1m ] $aEvent );
	then
	  System.out.println("---------------------------------MATCHING-TIME-OCCURS--------------------------------------");
end